import type { Product } from "./product.type"
export const products: Product[] = [
  {
    id: "iphone-17-pro",
    name: "iPhone 17 Pro",
    brand: "Apple",
    category: "Phones",
    price: 1500000,
    image: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd",
    rating: 4.8,
    stock: 12,
    description: "A powerful Apple smartphone with excellent performance and camera capabilities.",
  },

  {
    id: "galaxy-s25-ultra",
    name: "Galaxy S25 Ultra",
    brand: "Samsung",
    category: "Phones",
    price: 1800000,
    image: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf",
    rating: 4.7,
    stock: 8,
    description: "A premium Samsung smartphone with a large display and powerful performance.",
  },

  {
    id: "macbook-air-m4",
    name: "MacBook Air M4",
    brand: "Apple",
    category: "Laptops",
    price: 2200000,
    image: "https://images.unsplash.com/photo-1517336714739-489689fd1ca8",
    rating: 4.9,
    stock: 6,
    description: "A lightweight laptop powered by Apple's M4 chip.",
  },

  {
    id: "hp-spectre-x360",
    name: "HP Spectre x360",
    brand: "HP",
    category: "Laptops",
    price: 1750000,
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853",
    rating: 4.6,
    stock: 10,
    description: "A premium HP convertible laptop designed for productivity and portability.",
  },

  {
    id: "airpods-pro-3",
    name: "AirPods Pro",
    brand: "Apple",
    category: "Headphones",
    price: 450000,
    image: "https://images.unsplash.com/photo-1588423771073-b8903fbb85b5",
    rating: 4.7,
    stock: 15,
    description: "Wireless earbuds with immersive audio and active noise cancellation.",
  },

  {
    id: "galaxy-buds-3",
    name: "Galaxy Buds 3",
    brand: "Samsung",
    category: "Headphones",
    price: 280000,
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df",
    rating: 4.5,
    stock: 20,
    description: "Samsung wireless earbuds designed for clear sound and everyday comfort.",
  },

  {
    id: "nikon-z6",
    name: "Nikon Z6",
    brand: "Nikon",
    category: "Cameras",
    price: 1900000,
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32",
    rating: 4.8,
    stock: 5,
    description: "A versatile Nikon mirrorless camera for photography and video.",
  },

  {
    id: "lg-oled-tv",
    name: "LG OLED Smart TV",
    brand: "LG",
    category: "TVs",
    price: 1200000,
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1",
    rating: 4.8,
    stock: 7,
    description: "A premium LG OLED television with vivid picture quality and smart features.",
  },

  {
    id: "tcl-qled-tv",
    name: "TCL QLED Smart TV",
    brand: "TCL",
    category: "TVs",
    price: 750000,
    image: "https://images.unsplash.com/photo-1593784991095-a205069470b6",
    rating: 4.5,
    stock: 9,
    description: "A TCL smart television with QLED display technology and smart entertainment features.",
  },

  {
    id: "huawei-powerbank",
    name: "Huawei 20000mAh Power Bank",
    brand: "Huawei",
    category: "Powerbanks",
    price: 85000,
    image: "https://images.unsplash.com/photo-1609592424824-6f7c7f9f1c6e",
    rating: 4.4,
    stock: 25,
    description: "A high-capacity power bank designed to keep your devices charged throughout the day.",
  },

  {
    id: "samsung-monitor",
    name: "Samsung 27-inch Monitor",
    brand: "Samsung",
    category: "Monitors",
    price: 420000,
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
    rating: 4.6,
    stock: 11,
    description: "A 27-inch Samsung monitor suitable for work, entertainment, and gaming.",
  },

  {
    id: "apple-watch-series-10",
    name: "Apple Watch Series 10",
    brand: "Apple",
    category: "Smartwatches",
    price: 650000,
    image: "https://images.unsplash.com/photo-1544117519-31a4b719223d",
    rating: 4.8,
    stock: 8,
    description: "A modern Apple smartwatch with health, fitness, communication, and smart features.",
  },

  {
    id: "ps5-slim",
    name: "PlayStation 5 Slim",
    brand: "Sony",
    category: "Game Consoles",
    price: 950000,
    image: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db",
    rating: 4.9,
    stock: 4,
    description: "A compact PlayStation console built for high-quality gaming and entertainment.",
  },
]